import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import request from 'supertest';
import { createApp } from '../app';
import { prisma } from '../config/database';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';

const app = createApp();

describe('Collaborations API State Machine', () => {
  let industryToken: string;
  let academicianToken: string;
  let industryOrgId: string;
  let academicianId: string;

  beforeAll(async () => {
    const passwordHash = await bcrypt.hash('password123', 10);

    const industryOrg = await prisma.organization.create({
      data: { name: 'Test Industry', type: 'INDUSTRY', domain: 'test.com', isVerified: true }
    });
    industryOrgId = industryOrg.id;

    const industryUser = await prisma.user.create({
      data: {
        role: 'INDUSTRY',
        name: 'Industry Rep',
        email: 'rep@test.com',
        passwordHash,
        organizationId: industryOrg.id,
        isVerified: true
      }
    });

    const academician = await prisma.user.create({
      data: {
        role: 'ACADEMICIAN',
        name: 'Dr. Test',
        email: 'dr@test.com',
        passwordHash,
        isVerified: true
      }
    });
    academicianId = academician.id;

    industryToken = jwt.sign(
      { id: industryUser.id, userId: industryUser.id, role: industryUser.role },
      process.env.JWT_SECRET || 'test-secret',
      { expiresIn: '1h' }
    );

    academicianToken = jwt.sign(
      { id: academician.id, userId: academician.id, role: academician.role },
      process.env.JWT_SECRET || 'test-secret',
      { expiresIn: '1h' }
    );
  });

  afterAll(async () => {
    // Delete notifications generated by the propose/status API calls
    await prisma.notification.deleteMany({
      where: { payload: { path: ['collaborationId'], not: '' } }
    });
    // Delete all test collaborations
    await prisma.collaboration.deleteMany({
      where: { academicianId }
    });
    // Delete test users
    await prisma.user.deleteMany({
      where: { email: { in: ['rep@test.com', 'dr@test.com'] } }
    });
    // Only delete the test organization if no Opportunities reference it
    const oppCount = await prisma.opportunity.count({ where: { organization: { name: 'Test Industry' } } });
    if (oppCount === 0) {
      await prisma.organization.deleteMany({ where: { name: 'Test Industry' } });
    }
  });

  const createProposal = async () => {
    const res = await request(app)
      .post('/api/collaborations/propose')
      .set('Cookie', [`token=${academicianToken}`])
      .send({
        industryId: industryOrgId,
        title: 'Test Proposal',
        description: 'Test Description',
        type: 'RESEARCH_COLLABORATION'
      });
    if (res.status !== 201) {
      throw new Error(`Failed to create proposal: ${res.status} ${JSON.stringify(res.body)}`);
    }
    return res.body.collaboration;
  };

  const updateStatus = async (id: string, status: string) => {
    return request(app)
      .patch(`/api/collaborations/${id}/status`)
      .set('Cookie', [`token=${industryToken}`])
      .send({ status });
  };

  it('PROPOSED → ACCEPTED should PASS', async () => {
    const collab = await createProposal();
    const res = await updateStatus(collab.id, 'ACCEPTED');
    expect(res.status).toBe(200);
    expect(res.body.collaboration.status).toBe('ACCEPTED');
  });

  it('PROPOSED → REJECTED should PASS', async () => {
    const collab = await createProposal();
    const res = await updateStatus(collab.id, 'REJECTED');
    expect(res.status).toBe(200);
    expect(res.body.collaboration.status).toBe('REJECTED');
  });

  it('PROPOSED → REVIEWING should PASS', async () => {
    const collab = await createProposal();
    const res = await updateStatus(collab.id, 'REVIEWING');
    expect(res.status).toBe(200);
    expect(res.body.collaboration.status).toBe('REVIEWING');
  });

  it('REVIEWING → ACCEPTED should PASS', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'REVIEWING');
    const res = await updateStatus(collab.id, 'ACCEPTED');
    expect(res.status).toBe(200);
  });

  it('REVIEWING → REJECTED should PASS', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'REVIEWING');
    const res = await updateStatus(collab.id, 'REJECTED');
    expect(res.status).toBe(200);
  });

  it('ACCEPTED → ACTIVE should PASS', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    const res = await updateStatus(collab.id, 'ACTIVE');
    expect(res.status).toBe(200);
  });

  it('ACTIVE → COMPLETED should PASS', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    await updateStatus(collab.id, 'ACTIVE');
    const res = await updateStatus(collab.id, 'COMPLETED');
    expect(res.status).toBe(200);
  });

  // Negative tests
  it('REJECTED → ACCEPTED should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'REJECTED');
    const res = await updateStatus(collab.id, 'ACCEPTED');
    expect(res.status).toBe(409);
  });

  it('REJECTED → ACTIVE should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'REJECTED');
    const res = await updateStatus(collab.id, 'ACTIVE');
    expect(res.status).toBe(409);
  });

  it('COMPLETED → PROPOSED should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    await updateStatus(collab.id, 'ACTIVE');
    await updateStatus(collab.id, 'COMPLETED');
    const res = await updateStatus(collab.id, 'PROPOSED');
    expect(res.status).toBe(400);
  });

  it('COMPLETED → REJECTED should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    await updateStatus(collab.id, 'ACTIVE');
    await updateStatus(collab.id, 'COMPLETED');
    const res = await updateStatus(collab.id, 'REJECTED');
    expect(res.status).toBe(409);
  });

  it('COMPLETED → ACCEPTED should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    await updateStatus(collab.id, 'ACTIVE');
    await updateStatus(collab.id, 'COMPLETED');
    const res = await updateStatus(collab.id, 'ACCEPTED');
    expect(res.status).toBe(409);
  });

  it('ACTIVE → REJECTED should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    await updateStatus(collab.id, 'ACTIVE');
    const res = await updateStatus(collab.id, 'REJECTED');
    expect(res.status).toBe(409);
  });

  it('ACCEPTED → REJECTED should FAIL', async () => {
    const collab = await createProposal();
    await updateStatus(collab.id, 'ACCEPTED');
    const res = await updateStatus(collab.id, 'REJECTED');
    expect(res.status).toBe(409);
  });
});
